ci: IFS-2857 added setup script and playbook for building the documentation locally

diff --git a/.github/workflows/antora_build.yml b/.github/workflows/antora_build.yml
--- a/.github/workflows/antora_build.yml
+++ b/.github/workflows/antora_build.yml
@@ -7,7 +7,8 @@ on:
   workflow_dispatch:
     inputs:
       distinct_id:
-        description: 'The distinct id of the workflow run'
+        # Used by codex-/return-dispatch action from another workflow to keep track of the run. Manual runs using the UI do not require this input.
+        description: 'The distinct id of the workflow run (optional)'
 
 jobs:
   Build:
@@ -15,8 +16,13 @@ jobs:
     env:
       MAVEN_CLI_OPTS: '--batch-mode --errors --fail-at-end -T 1C'
 
+      # Define color variables
+      RED: '\033[0;31m'
+      GREEN: '\033[0;32m'
+      NC: '\033[0m' # No Color
+
     steps:
-      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
+      - name: Get distinct ID ${{ github.event.inputs.distinct_id }}
         run: echo ${{ github.event.inputs.distinct_id }}
 
       - name: Checkout
@@ -26,7 +32,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: IsyFact/isyfact-standards
-          ref: feature/ISY-998-Analyse_Sichtbarkeit_der_Doku_Warnungen
+          ref: master
           lfs: true
           sparse-checkout: isyfact-standards-doc/src/docs/antora
           path: isyfact-standards
@@ -145,12 +151,14 @@ jobs:
         run: npm ci
       - name: Build Documentation
         run: |
-          npm run build
-          exit_code=$?
+          npm run build || BUILD_FAILED=true
+          
           # Check exit code of antora build command
-          if [ $exit_code -ne 0 ]; then
-            echo "Antora build failed with exit code $exit_code. Exiting workflow."
-            exit $exit_code
+          if [ "$BUILD_FAILED" = true ]; then
+              echo -e "${RED}Antora documentation build failed with exit code $exit_code.${NC}"
+              exit $exit_code
+          else
+            echo -e "${GREEN}Antora documentation build completed successfully.${NC}"
           fi
 
       - name: Upload artifact
