ci: handle build exit code

diff --git a/.github/workflows/antora_build.yml b/.github/workflows/antora_build.yml
--- a/.github/workflows/antora_build.yml
+++ b/.github/workflows/antora_build.yml
@@ -26,7 +26,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: IsyFact/isyfact-standards
-          ref: feature/ISY-998-Analyse_Sichtbarkeit_der_Doku_Warnungen
+          ref: master
           lfs: true
           sparse-checkout: isyfact-standards-doc/src/docs/antora
           path: isyfact-standards
@@ -85,12 +85,14 @@ jobs:
         run: npm ci
       - name: Build Documentation
         run: |
-          npm run build
-          exit_code=$?
+          npm run build || BUILD_FAILED=true
+          
           # Check exit code of antora build command
-          if [ $exit_code -ne 0 ]; then
-            echo "Antora build failed with exit code $exit_code. Exiting workflow."
-            exit $exit_code
+          if [ "$BUILD_FAILED" = true ]; then
+              echo "Antora documentation build failed with exit code $exit_code."
+              exit $exit_code
+          else
+            echo "Antora documentation build completed successfully."
           fi
 
       - name: Upload artifact
